### ISSUE TITLE
How to install it with alias?

### ISSUE THREAD

**Issue by RafaelPlantard** [staskjs/vue-slick#1]
Can explain?

**Comment by staskjs** [comment]
In your webpack config there is `resolve.alias` option. You can point jquery to one path.
```javascript
resolve: {
  alias: {
    jquery: path.join(__dirname, 'node_modules', 'jquery', 'dist', 'jquery'),
  }
}
```
This will point jquery that official slick package is using to the same path.

**Comment by RafaelPlantard** [comment]
And how about peer dependency? Can show me?

**Comment by staskjs** [comment]
This is not something you can solve by yourself, I guess, but Slick maintainers can. Anyway I think aliases will work just fine in these kind of scenarios.

**Comment by RafaelPlantard** [comment]
Thanks
