### ISSUE TITLE
Not support dynamic data (from firebase for example)

### ISSUE THREAD

**Issue by kenyk7** [staskjs/vue-slick#10]

**Comment by staskjs** [comment]
Provide a code example please.

**Comment by kenyk7** [comment]
https://www.webpackbin.com/bins/-Kgmb2T18ty4lS7hVr1R

**Comment by staskjs** [comment]
Ok I added a `reSlick` method. Use it on your firebased slick AFTER data is loaded, it should redraw itself then.

**Comment by kenyk7** [comment]
Ok, the next problem is that exists a bug when switching slide or add new item.
See demo: https://www.webpackbin.com/bins/-Kgmb2T18ty4lS7hVr1R

**Comment by staskjs** [comment]
Try using reSlick method here too. Call it when new item is added.

**Comment by kenyk7** [comment]
Thank you, the idea was not to reinstall many times the slick but to listen to the changes of the array and do it automatically, but okay.
