### ISSUE TITLE
@SerlokPK, I wouldn't use VueSlickCarousel. I found a nasty bug that traps the users' vertical touch on mobile devices. I've filed it in the issues section but got no response, so I moved over to this build of slick because the bug doesn't exist and has more community support anyway.

### ISSUE THREAD

**Issue by madridMMadrid** [staskjs/vue-slick#102]
СПАСИБО!!)))

**Comment by spiritbro1** [comment]
hello which one you use now?

**Comment by priosshrsth** [comment]
Ok, I also seem to have a bug with slick slider, on touch devices when scrolling vertically by touching the slider.
The slider, then shows all of the slides at once, with really long height, and all slides width becomes so, small, that, everything looks like a long vertical line in my page.
This doesn't happend, if I avoid touching the slider while scrolling. Also, everything works fine on desktop/laptop.
