### ISSUE TITLE
"cannot find module 'vue-slick'" with TypeScript

### ISSUE THREAD

**Issue by lukasIO** [staskjs/vue-slick#15]
Hi, 
I wanted to try the plugin, but when I try to import it into my main.ts file, I get the error that the module cannot be found. 
I installed it with npm (once with, once without the --save option), made sure it is listed under dependencies in the package.json, but still, it cannot be found...
any idea why?
thanks!

edit: managed to get it to work by adding a index.js to the plugin folder with 
`exports.Slick = require('./slickCarousel')`

**Comment by staskjs** [comment]
I am not using typescript myself, by looking at your solution, probably typescript ignores `main` field in package.json. Please make a pull request.

**Comment by lukasIO** [comment]
it was a bit premature, still didn't work properly in the end, and I didn't follow the issue further until now...
