### ISSUE TITLE
slickAdd

### ISSUE THREAD

**Issue by mmdonaldson** [staskjs/vue-slick#16]
Does the element argument here
```
    add(element, index, addBefore) {
      $(this.$el).slick('slickAdd', element, index, addBefore);
    },
```
Need to be html or can it be a vue component

**Comment by staskjs** [comment]
Slick only understands html.

**Comment by mmdonaldson** [comment]
Do you know if there is a way/best practivce to render a component to html. Like in React, dangerouslySetInnerHtml

**Comment by staskjs** [comment]
You probably can use v-for to render an array of components inside slick. Then just add new item to this array and call `reSlick` method.
