### ISSUE TITLE
No destroy method

### ISSUE THREAD

**Issue by felgeekpe** [staskjs/vue-slick#17]
You have a method to reInit the carousel, but what if i want to only 'unslick' without creating it again.
can we add a destroy method? like this one:
`destroy() {
      $(this.$el).slick('unslick');
},`

**Comment by felgeekpe** [comment]
Added a pull request with the change
https://github.com/staskjs/vue-slick/pull/18

**Comment by staskjs** [comment]
Thanks. Merged.
