### ISSUE TITLE
Can't run Vue-slick

### ISSUE THREAD

**Issue by tuannguyenminh2086** [staskjs/vue-slick#25]
Hi, 
After install, I got the issue:
<img width="854" alt="screen shot 2017-07-05 at 3 03 01 pm" src="https://user-images.githubusercontent.com/1555621/27855042-27ef3288-6193-11e7-8550-53394c19275a.png">

**Comment by staskjs** [comment]
You have to use vue plugin for your bundling system (for example vue-loader if you use webpack), because vue-slick is distributed as single file vue component.
