### ISSUE TITLE
How start with v-for

### ISSUE THREAD

**Issue by majweb** [staskjs/vue-slick#27]
i have this code and slick not run 
`<div v-for="allpictures in allphotos" class="single">
       <p class="bg-blue text-default text-center">{{allpictures.type}}</p>
       <li><img v-if="allpictures.gallery == ''" :src="'/storage/admin/cwiczenia/user.png'" alt=""
                                     class="img-responsive"></li>
        <ul v-for="picture in allpictures.gallery">
               <li><img v-if="picture" :src="'/storage/admin/cwiczenia/'+picture.photo" alt="" class="img-responsive" ></li>
        </ul>
     </div>`

**Comment by staskjs** [comment]
There is no vue-slick in your code. Try wrapping it around ul
