### ISSUE TITLE
How to add thumbs?

### ISSUE THREAD

**Issue by jasonlam0619** [staskjs/vue-slick#3]
According to slick's official site, there are `slide-for` and `slide-nav`.

```js
 $('.slider-for').slick({
  slidesToShow: 1,
  slidesToScroll: 1,
  arrows: false,
  fade: true,
  asNavFor: '.slider-nav'
});
$('.slider-nav').slick({
  slidesToShow: 3,
  slidesToScroll: 1,
  asNavFor: '.slider-for',
  dots: true,
  centerMode: true,
  focusOnSelect: true
});
```

But how to realize it in vue-slick?

**Comment by staskjs** [comment]
Provided examples should work just as you would expect. Add classes to slick elements and cross-reference them in asNavFor options.

**Comment by jasonlam0619** [comment]
@staskjs No, won't work

**Comment by staskjs** [comment]
Could you provide an example of how are you doing it?
