### ISSUE TITLE
How can I use beforeChange Events

### ISSUE THREAD

**Issue by ayaz323** [staskjs/vue-slick#31]
when change slide with click or swipe I will check last slide ? how can I this  

<slick ref="slick" :options="slickOptions" class="slicks">
        <a v-for="(list,index) in lists" :key="index"
          :href="list.detailUrl"
          class="box-">
          <figure>
             <img :src='list.logo '   :alt="list.firm">
          </figure>
          <strong>{{list.title}}</strong>
          <span>{{list.companyName}}</span>
        </a>
      </slick>

 <button type="button" @click="prev" data-role="none" class="lastsearch-prev-arrow slick-arrow" aria-label="Previous" role="button" style="">
          <i class="moon-left-arrow"></i>
        </button>
        <button type="button" @click="next" data-role="none" class="lastsearch-next-arrow slick-arrow" aria-label="Previous" role="button" style="">
          <i class="moon-right-arrow"></i>
        </button>

**Comment by staskjs** [comment]
Try adding `@before-change="doSmth"`

**Comment by whereo** [comment]
Sorry for reopening the issue.
I'm trying to use the events as well, but don't get the parameters like `slick`, `currentSlide` or `nextSlide`

```javascript
// template
<slick ref="slick" class="slider" :options="slickOptions" @beforeChange="beforeChange">

...

methods: {
    beforeChange($event, slick, current, next) {
        console.log(current);
        console.log(next);
    },
}
``` 
Both, `current` and `next` are undefined. What am I missing?
