### ISSUE TITLE
reSlick not properly reinitializing component with v-for

### ISSUE THREAD

**Issue by hackel** [staskjs/vue-slick#32]
I'm trying to use this component to render a list of images which is dependent on a state variable.  When the page loads (currentDamage=0, damagePhotos.length=1), everything renders correctly.  When I migrate to (currentDamage=1, damagePhotos.length=0), the old image remains displayed.  When I then migrate back to (currentDamage=0, damagePhotos.length=1), another copy of the original image is added to #thumbnails for some reason.

Here's a stripped-down version of my component:
```vue
<template>
    <div id="thumbnails" class="col-sm-offset-1 col-sm-5">
        <slick ref="slick" :options="slickOptions">
            <div class="image" v-for="(photo, index) in damagePhotos">
                <img class="preview-img" :src="photo.thumbnail">
            </div>
        </slick>
    </div>
</template>

<script>
    import { mapState, mapGetters } from 'vuex';
    import Vue from 'vue';
    import Slick from 'vue-slick';

    export default {
        computed:   {
            ...mapState(['currentDamage']),
            ...mapGetters(['damagePhotos']),
        },
        watch:      {
            currentDamage() {
                Vue.nextTick().then(this.reInit);
            },
        },
        /* I also tried this with the same result
        updated() {
            Vue.nextTick().then(this.reInit);
        },
        */
        components: {Slick},
        data() {
            return {
                slickOptions: {
                    dots:           true,
                    lazyLoad:       'ondemand',
                    slidesToShow:   4,
                    slidesToScroll: 3,
                },
            };
        },
        methods:    {
            reInit() {
                this.$refs.slick.reSlick();`
            },
        },
    };
</script>
```

I've tried many combinations here, using watch and updated, and adding the nextTick trick which I read in another bug report, but nothing seems to help.  Any insight would be greatly appreciated!

Possibly a dupe of #5, but @packytagliaferro closed it without giving any solution.

Edit: I found a workaround, by adding `v-if="damagePhotosWithoutFirst.length > 0"`, but this is not really a solution to the issue.

**Comment by hackel** [comment]
Found an even better work-around,  but it's going to require me to re-think my methodology, since I'm actually changing currentDamage in a separate component.  Am I missing something?  It seems like it just shouldn't be this complicated.
```js
    setCurrentDamage(index) {
        this.$refs.slick.destroy();
        this.$store.commit('setCurrentDamage', index);
        Vue.nextTick().then(this.$refs.slick.create);
    },
```

**Comment by staskjs** [comment]
There is no method in original plugin to reinitialize slick, so I had to create this reSlick method, which worked in some situations. Maybe we can add your workaround into a reSlick function which would work like this:
```javascript
this.$refs.slick.reSlick(() => {
  this.$store.commit('setCurrentDamage', index);
});
```

So basically if function is passed to reSlick, it will call it between destroy and create. Could you check this out in your code and make a pull request if it works?

**Comment by hackel** [comment]
The issue is I'm actually calling setCurrentDamage from a completely different component.  What I finally landed on doing was this:
```js
        beforeUpdate() {
            if (this.$refs.slick) {
                this.$refs.slick.destroy();
            }
        },
        updated() {
            if (this.$refs.slick && !this.$refs.slick.$el.classList.contains('slick-initialized')) {
                this.$refs.slick.create();
            }
        },
```
A little convoluted, but it seems to be working fine.

**Comment by staskjs** [comment]
Convoluted indeed. Alright then.

**Comment by CyberStrike** [comment]
This solution was what saved me after 3 Days of head bashing.

**Comment by AndrewSavetchuk** [comment]
Thanks a lot
