### ISSUE TITLE
Passing ref nodes to prevArrow and nextArrow options isn't working

### ISSUE THREAD

**Issue by docmars** [staskjs/vue-slick#35]
Hey there,

I'm trying to assign Slick a couple of nodes for its next/prev buttons since it annoyingly hides its arrows when there aren't enough slides to go past its container.

_BTW, if you do know of a good way to **always** show its built-in arrows regardless of its state, that would be a better solution. I'm going to need to somehow implement the `disabled` state when it reaches an edge, which Slick also doesn't provide, unfortunately._

**The Problem**
Passing in the refs to Slick's options simply doesn't work. Clicking the arrows yields no movement, despite having a handful of items in the carousel.

**Here's what I've got:**
```html
<button type="button" class="slick-prev" ref="prevArrow"></button>
<button type="button" class="slick-next" ref="nextArrow"></button>
<slick ref="slick" :options="slickOptions"></slick>
```

```javascript
data() {
  return {
    slickOptions: {
      arrows: false,
      prevArrow: this.$refs.prevArrow,
      nextArrow: this.$refs.nextArrow
    }
  }
}
```

Any help would be appreciated. Thanks!

**Comment by staskjs** [comment]
As long as slickOptions is passed directly into slick plugin, it relies on selectors for prevArrow and nextArrow. Did you try to use selectors?

**Comment by docmars** [comment]
@staskjs I did, and it was a no-go. Nothing I threw at it worked for those options for some reason. :/

I ended up hacking away at adding custom arrows with the library's methods. I may just skip the disabled state altogether when it's at either edge.

**Comment by staskjs** [comment]
Could you post a solution here in code?

**Comment by docmars** [comment]
Unfortunately I don't have much time to do that—I'm under a tight deadline. Sorry!

I think in the future I may just implement my own carousel in Vue.js when it's necessary. Slick's great, but it has some firm limitations that deter from the experience we're going for. I generally am not a fan of libraries that include their own UI that I almost always have to fight with. :/

If I can find a little time in the future I'll see if I can whip something up in a CodePen.

Thanks for being supportive on this issue, I appreciate your help. 😄

**Comment by staskjs** [comment]
Ok then. Good luck!

**Comment by vesper8** [comment]
Not sure why you needed to use a ref so bad, but using selectors works fine:

```
  data() {
    return {
      slickOptions: {
        infinite: true,
        slidesToShow: 3,
        slidesToScroll: 3,
        arrows: true,
        prevArrow: '#gallery-prev',
        nextArrow: '#gallery-next',
      },
    };
  },
```

**Comment by anankitpatil** [comment]
Did you find a solution for this? Selectors aren't working for me.
