### ISSUE TITLE
"TypeError: $slick.slick is not a function"

### ISSUE THREAD

**Issue by nexflo** [staskjs/vue-slick#36]
I'm getting this error..and im fairly certain its todo with jquery.
You do mention:
NOTE: slick-carousel official package appears to use jquery as a dependency in package.json, despite it would be more appropriate to use it as a peer dependency to avoid possibility of using multiple versions of jquery. Be aware of that. When using webpack you can solve this problem with aliases.

Could you paste the best practices approach here?
Tried aliases and provideplugins but still getting errors.
https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack?answertab=active#tab-top

**Comment by staskjs** [comment]
This just means you need to add `jquery: path.join(__dirname, 'node_modules', 'jquery', 'dist', 'jquery')` to point jquery to specific file. This may not be the case with newer webpack versions.
