### ISSUE TITLE
Carousel full width shows on page

### ISSUE THREAD

**Issue by arjanski** [staskjs/vue-slick#37]
Hello, 

First of all thank you Stanislav for your work, great to see a Vue Slick adaption! I reallyhope I can get it to work.

My issue is that while all interactivity seems to work basically, the containing div with class "slick-track" shows in full width on my page, so it is not hiding any 'hidden' slick elements when sliding. The result is this (page should end where image ends):

![23-18-2017_05 18 38-capturfiles](https://user-images.githubusercontent.com/13831998/29623815-db73f41e-8827-11e7-99ea-53f062b739b5.jpg)

The console says

![23-19-2017_05 19 18-capturfiles](https://user-images.githubusercontent.com/13831998/29623825-e1428fb8-8827-11e7-9d8d-231916fe7bfd.jpg)

Does anyone have an idea why this is happening?

This is my code for the slides:

![23-29-2017_05 29 45-capturfiles](https://user-images.githubusercontent.com/13831998/29624164-af592448-8828-11e7-861b-62456de17567.jpg)

and this are my Slick options right now:

`      slickOptions: {
                slidesToShow: 3,
                swipeToSlide: true,
                arrows: false,
                infinite: true
                // Any other options that can be got from plugin documentation
         }`

**Comment by arjanski** [comment]
A work-around is to give the encapsulating <div> a style of "overflow-x: hidden", but probably not the tidiest of solutions.

**Comment by staskjs** [comment]
Hello. Try including slick styles in your project. There are few words about it in readme. Hope this helps.

**Comment by arjanski** [comment]
Thanks! That did the trick (should have tried that right away). I do have a strange bug though - slick seemingly bloats my 350x300px images to 475px when loading, sometimes after a few seconds of autoplay. 

Have you ever encountered this? The slick div only consists of images:

![24-15-2017_02 15 40-capturfiles](https://user-images.githubusercontent.com/13831998/29666113-48110cd8-88d7-11e7-9e0f-0383e9c01dea.jpg)

Thank you very much for your help!

**Comment by monkemedia** [comment]
Apply this to your css

.slick-slider {
    width: 100%
    max-width: 720px // The widest it will go on a responsive website
}

Hope this helps
