### ISSUE TITLE
Combination with nuxt.js doesn't work

### ISSUE THREAD

**Issue by coolemur** [staskjs/vue-slick#38]
Test case:

Add slick to your nuxt.js page.
Refresh page.
Slick lib ERROR appears.

Template example:

```
<template>
  <section class="monoStaff">
    <div class="container container--fluid">
      <div class="row center-xs">
        <div class="col-xs col-sm col-md col-lg">
          <h1>{{data.title}}</h1>
        </div>
      </div>
      <div class="row">
        <slick ref="slick" :options="slickOptions">
          <a href="http://placehold.it/100x50"><img src="http://placehold.it/100x50" alt=""></a>
          <a href="http://placehold.it/100x50"><img src="http://placehold.it/100x50" alt=""></a>
          <a href="http://placehold.it/100x50"><img src="http://placehold.it/100x50" alt=""></a>
          <a href="http://placehold.it/100x50"><img src="http://placehold.it/100x50" alt=""></a>
          <a href="http://placehold.it/100x50"><img src="http://placehold.it/100x50" alt=""></a>
        </slick>

      </div>
      <div class="row center-xs">
        <div class="col-xs col-sm col-md col-lg">
          <h2>{{data.subtitle}}</h2>
        </div>
      </div>
    </div>
  </section>
</template>
```

Add slick code sample:

```
import Slick from 'vue-slick'
import '~/node_modules/slick-carousel/slick/slick.css'
...
  components: {
    Slick
  }
...
```

**Comment by staskjs** [comment]
Could you create a jsfiddle for this?

**Comment by coolemur** [comment]
It’s nuxt.js project (https://nuxtjs.org/guide/installation).

I see no point to create jsfiddle. It’s ssr issue.

Simple reproduction of issue:
1. Create NUXT.JS project as a plugin.
2. Add slick to nuxt page.
3. Refresh page.

**Comment by staskjs** [comment]
What kind of error do you have?

**Comment by staskjs** [comment]
I am currently not really sure how to solve this. Don't have much time to dig in nuxt.js now. If you find a solution, please post an update or PR.

**Comment by coolemur** [comment]
```
Nuxt.js Error: /Users/MMac/MonoTwo/mk-sypsenosklinika/node_modules/vue-slick/slickCarousel.vue:1 (function (exports, require, module, __filename, __dirname) { <template> ^ SyntaxError: Unexpected token <
```

I won't find a solution, because vue slick isn't prepared for server-side rendering.

For now I will have to use other component which work with ssr.

Please check it, if you can, when you have more time. :)

**Comment by staskjs** [comment]
Fair enough.

**Comment by xloading** [comment]
Hi @coolemur and @staskjs !

I've found out that the problem was not related to incompatibility with Nuxt.
Instead it is caused by the fact that this plugin provides raw Vue component in package instead of ES/JS code (this was briefly covered in #62 ).

I've managed to handle this adding the following code in nuxt.config.js build section:
```js
extend (config, { isDev, isClient, isServer }) {
      if (isServer) {
        config.externals += [
          require('webpack-node-externals')({
            whitelist: [/^vue-slick/]
          })
        ]
      }
    }
```

**Comment by Atinux** [comment]
@xloading you can use `build.transpile` with Nuxt-edge (and Nuxt 2 coming).

Demo: https://glitch.com/edit/#!/nuxt-vue-slick
Code: https://glitch.com/edit/#!/nuxt-vue-slick?path=nuxt.config.js:10:6

**Comment by sameerpanjwani** [comment]
@Atinux your demo doesn't work, it shows an error of Window not being defined.

**Comment by xloading** [comment]
The same issue here after updating Nuxt from 1.4.1 to 2.3.4

**Comment by WanyoikeJ** [comment]
Has anyone found a solution to this? am getting the same issue too.
`window is not defined`

**Comment by Yitta** [comment]
> Has anyone found a solution to this? am getting the same issue too.
> `window is not defined`

You can try this method:
https://stackoverflow.com/questions/53806318/window-is-not-defined-nuxt-for-vue-slick

**Comment by arifhussain353** [comment]
@Yitta I only import component like this and my problem solved. 

```
 components: {          
      Slick: () => import('vue-slick')
  }
```

**Comment by machacek-iw** [comment]
@arifhussain353 This works but still show warn message. This solved the whole problem for me:

`components: {
        Slick: () => (typeof window !== 'undefined') ? import('vue-slick') : undefined
    },`

**Comment by loctdvn** [comment]
I have resolved problem 

1/ Create plugin file
/plugins/slick-slide.js

```
import Vue from 'vue';
import Slick from 'vue-slick';

const SlickSlide = {
  install(Vue, options) {
    Vue.component('slick-slide', Slick)
  }
};

Vue.use(SlickSlide);
export default SlickSlide;
```

2/ In nuxt.config.js
```
plugins: [
    { src: "~plugins/slick-slide.js", ssr: false }
],
```

3/ In component: `abc.vue`

```
<template>
  <no-ssr>
		<slick-slide
			ref="slick"
			:options="slickOptions">
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
			<a href="http://placehold.it/2000x1000"><img src="http://placehold.it/2000x1000" alt=""></a>
		</slick-slide>
	</no-ssr>
</template>

<script>

export default {
	data() {
		return {
			slickOptions: {
				slidesToShow: 4,
				slidesToScroll: 4,
			},
		};
	},
}
</script>
```

**Comment by cenamorado** [comment]
@loctdvn  hey dude thanks you safe my life

**Comment by loctdvn** [comment]
Hi you
I'm so happy, thank you

Vào Th 6, 28 thg 2, 2020 lúc 11:49 Christopher Enamorado <
notifications@github.com> đã viết:

**Comment by mattkaye** [comment]
@loctdvn has a great working solution. One thing I did notice though is you don't need the `<no-ssr>` tag wrap in the component. Thanks again!

**Comment by loctdvn** [comment]
Yes, thank you 👍👍👍

Vào Th 6, 15 thg 5, 2020 lúc 02:43 Matt Kaye <notifications@github.com> đã
viết:

**Comment by manuel-gutierrez** [comment]
Just a quick update  on @loctdvn solution: <no-ssr></no-ssr> wrapper should be replaced by <client-only></client-only>  as it will be depreciated soon: https://nuxtjs.org/api/components-client-only/
