### ISSUE TITLE
Reslick might not work as intended

### ISSUE THREAD

**Issue by morph85** [staskjs/vue-slick#39]
I'm having issue using vue-slick with items that was loaded from server. Reslick function doesn't work as intended. I am seeing the div or a href stack up block by block below inside the control.

Unless that, if i'm using workaround like this, then only it would work:

```
// assign items here:
this.items = items // loaded from ajax or axios call

setTimeout(function () {
  this.reInit()
}.bind(this), 1000)
```

Is there any better way of doing this?

**Comment by staskjs** [comment]
Probably reason is that vue is not getting updated right away when you assign new value to `items`. Try this instead of timeout:
```
this.$nextTick(function () {
  this.reInit();
});
```

**Comment by morph85** [comment]
Works like magic! Thanks.
