### ISSUE TITLE
Slick Events

### ISSUE THREAD

**Issue by JulsWlf** [staskjs/vue-slick#4]
I'm attempting to use slick events on your component, but I can't get it to work.

I'm passing in an event listener like `@afterChange` (this is a Slick event according to its documentation) to the main `slick` element, but it just gets removed.

Sorry if this is a fault on my side, im new to Vue.js

Calling the component like so: (its PUG templating.)
test is a method I registered.
```
slick.carousel(:options="slickOptions", @afterChange="test")
```

if I bind a click event to the children, it works, but not on the parent.

Thanks in advance!

**Comment by staskjs** [comment]
Component wasn't supporting events. Now it does. Thanks for reminding. Use version 1.1
