### ISSUE TITLE
A way to set it globaly

### ISSUE THREAD

**Issue by Aterr** [staskjs/vue-slick#40]
Hi there!
trying to init slick slider with:
`Vue.use(Slick)`

but it doesn't work.
I would be very thankful for help :)

**Comment by staskjs** [comment]
There is no way to use `Vue.use` currently. Try this:

    import Slick from 'vue-slick';
    Vue.component('slick', Slick)

**Comment by Aterr** [comment]
Thanks, it worked for me. 👍
