### ISSUE TITLE
How use reInit function

### ISSUE THREAD

**Issue by applejp** [staskjs/vue-slick#42]
When i use v-for to update dynamic lists, how should i use reInit function to deal with new lists?

**Comment by staskjs** [comment]
Try to wrap it in Vue.nextTick function.

**Comment by Aterr** [comment]
I have similar problem.

I am retrieving data from the server and I have v-for for render items.
When I am launching reInit function, console throws me an error: 
```
[Vue warn]: Error in nextTick: "TypeError: _this.$refs.slick is undefined"
```

any ideas ?

**Comment by staskjs** [comment]
Can you show your code?
