### ISSUE TITLE
slick.reSclick is not re-intializing slick when trying to get data dynamically using v-for

### ISSUE THREAD

**Issue by naveen84123** [staskjs/vue-slick#44]
vue-slick is working fine with static content.
But when I am trying to loop through playlists of user.slick is not working.

html part:

    <template>
        <slick ref="slickone" :options="slickOptions">
            <div v-for='playlist in user_playlists'>
                <a href="#">
                    <img :src="playlist.image">
                    <p>Playlist Name</p>
                </a>
            </div>

        </slick>
    </template>

script part:

    <script>
        import Slick from 'vue-slick';
        import './node_modules/slick-carousel/slick/slick.css';
        import './node_modules/slick-carousel/slick/slick-theme.css';
        export default {
            data() {
                return {
                    user_playlists: [],
                    slickOptions: {
                        infinite: true,
                        slidesToShow: 5,
                        slidesToScroll: 1,
                        autoplaySpeed: 5e3,
                    },
                };
            },
            methods: {
                getUserPlaylists() {
                    this.$http.get('api/user_playlists/user-playlists')
                            .then(response => {
                                this.user_playlists = response.body.data;
                                this.$refs.slickone.reSlick();
                            });
                },
                updated() {
                    this.reInit();
                },
                reInit() {
                    this.$refs.slickone.reSlick();
                },
            },
            components: {
                'slick': Slick,
            },
            watch: {
                profileData() {
                    this.getUserPlaylists();
                },
                user_playlists() {
                    this.reInit();
                }
            }
        }
    </script>
I have checked the documentation and used `this.$ref.slickone.reSlick()` but still its not working.
Please help me out with this.

**Comment by staskjs** [comment]
Try this:
```
Vue.nextTick(() => {
  this.$refs.slickone.reSlick();
});
```

**Comment by kevin-coyle** [comment]
I'm getting the same issue as this. It's coming up that reSlick() is not defined.

**Comment by kevin-coyle** [comment]
Ah my issue is because i have multiple slicks on one page. In this case this.$refs.slick returns an array.

**Comment by naveen84123** [comment]
then what can we do, if we have multiple slicks on the page?

**Comment by staskjs** [comment]
Call reslick for each of the array? Or call refs differently

**Comment by jimmi-joensson** [comment]
I never got reSlick to work, however I found a fix to load out the elements with v-for.

Template:
`
<slick ref="slick" :options="slickOptions" v-if="showSlick">
	<div v-for="( item, index ) in feed">
		<h3>{{ index + 1 }}</h3>
	</div>
</slick>
`
Script:
`
export default {
	components: {
		Slick,
	},
	data() {
		return {
			feed: [],
			slickOptions: {
				slidesToShow: 4,
				slidesToScroll: 4,
			},
		};
	},
	computed: {
		showSlick() {
			return this.feed.length > 0;
		}
	},
`
