### ISSUE TITLE
Carousel unslicks before transition completes because unslick called on beforeDestroy

### ISSUE THREAD

**Issue by lukechinworth** [staskjs/vue-slick#46]
Thanks for the great component!

I am using it in a page that fades out before the next page fades in using vue's `transition` component. But when the transition starts, the `beforeDestroy` callback is called, which for `vue-slick` calls `unslick`. This causes the carousel to distort back to the original markup as the transition takes place.

Would it be better to `unslick` in the `destroyed` callback after the transition is complete?

**Comment by staskjs** [comment]
Good idea. Could you please make a PR for this?
