### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by yustik** [staskjs/vue-slick#50]
One question i want it to use the responsive options from Slick 

`responsive: [
                {
                    breakpoint: 1200,
                    settings: {
                        arrows: false,
                        slidesToShow: 4
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                        arrows: false,
                        slidesToShow: 3
                    }
                },
                {
                    breakpoint: 576,
                    settings: {
                        arrows: false,
                        slidesToShow: 2
                    }
                }
            ]`

But seems not to work in vue, there is a workaround for this in the component?

**Comment by buroli** [comment]
Any solution for that ?

**Comment by kamilmaliszewski** [comment]
For me it also doesnt work. there is any fix for it?

**Comment by shkodasv** [comment]
Any updates ?

**Comment by kamilmaliszewski** [comment]
It works for me. Be sure that you put "responsive" in slickOptions object which is forward to vue-slick component

```
slickOptions: {
          slidesToShow: 4,
          slidesToScroll: 4,
          infinite: false,
          arrows: false,
          responsive: [
            {
              breakpoint: 1024,
              settings: {
                slidesToShow: 3,
                slidesToScroll: 2
              }
            },

            {
              breakpoint: 767,
              settings: {
                slidesToShow: 2,
                slidesToScroll: 2
              }
            },
            {
              breakpoint: 639,
              settings: {
                slidesToShow: 1,
                slidesToScroll: 1
              }
            },
          ]
        },
```

**Comment by shkodasv** [comment]
will try. thx!

**Comment by Micah789** [comment]
I am getting the same almost like the component is removing inline styling I use to show the background image
