### ISSUE TITLE
How I can use appendDots?

### ISSUE THREAD

**Issue by mrKorg** [staskjs/vue-slick#51]
I have options
`
slickOptions1: {
                    dots: true,
                    appendDots: document.getElementById('mainSlider__dots1'),
                    arrows: false,
                    infinite: true,
                    speed: 500,
                    fade: true,
                    cssEase: 'linear'
                },
`
But dots there does not appear.

**Comment by Eliston** [comment]
Hello,
Any solution about appendDot please ?

**Comment by marko-mlinarevic** [comment]
did anyone was able to solve it
