### ISSUE TITLE
Transition issue because of destroyed() hook

### ISSUE THREAD

**Issue by pschaub** [staskjs/vue-slick#56]
The slick will be "unslicked" on the `destroyed` hook. That results into a broken layout if the developer is using page transitions (e.g. on leaving a route). The reason behind this is that the `unslick` command will remove all slick classes and information from the DOM elements.

See also: https://github.com/vuejs/vue/issues/6983

There should be a way to wait for the transition to finish before `unslick` happens.

This can be easily reproduced with 2 pages and a very slow page route transition.

```
<transition name="route-transition-fade" mode="out-in">
    <router-view :key="$route.path"/>
</transition>
```

```
.route-transition-fade-enter-active, .route-transition-fade-leave-active {
  transition: opacity 500s ease;
}

.route-transition-fade-enter, .route-transition-fade-leave-to {
  opacity: 0;
}
```

**Comment by josephahern** [comment]
Has a solution for this been determined yet? Would love to continue using slick-slider with vue!

**Comment by ArkhipovK** [comment]
Just faced this problem

**Comment by radiantstatic** [comment]
@ArkhipovK - I ended up doing something like this had to dig through commit history as we ended up not using slick in the end.

In slickCarousel.vue

`destroyed() {
+    const manualDestroy = () => {
+      $(this.$el).slick('unslick');
+      console.log('unslicked');
+      this.$el.removeEventListener(manualDestroy);
+    };
+    this.$el.addEventListener('transitionend', manualDestroy);
+  },`

**Comment by khudia** [comment]
Doesn't help ((
How to disable destroy method on transition?

**Comment by khudia** [comment]
How to disable destroy hook?

**Comment by diachedelic** [comment]
@khudia maybe check out https://github.com/diachedelic/vue-removed-hook-mixin

**Comment by mnlauaa** [comment]
@diachedelic I got an error because this.$options.removed is undefined

**Comment by diachedelic** [comment]
> @diachedelic I got an error because this.$options.removed is undefined

did you define a `removed` hook in your component? Check the example usage in the readme

**Comment by NickolayBauer** [comment]
You can hide the slick after the animation starts. No slick - no problem.

```scss
fade-leave-active {
  .--you-block-with-slick-- {
    opacity: 0;
    display: none;
  
```
