### ISSUE TITLE
Module not found: Error: Can't resolve 'jquery'

### ISSUE THREAD

**Issue by DulanHewage** [staskjs/vue-slick#58]
`in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-slick/slickCarousel.vue
Module not found: Error: Can't resolve 'jquery' in 'D:\xxxx\lia-shahar-pwa\node_modules\vue-slick'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-slick/slickCarousel.vue 8:0-23
 @ ./node_modules/vue-slick/slickCarousel.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/product-category-list.vue
 @ ./src/components/product-category-list.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/home.vue
 @ ./src/components/home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js`

**Comment by ChristianMurphy** [comment]
`vue-slick` has jQuery as a peer dependency.
https://github.com/staskjs/vue-slick/blob/6e30eea334f287fc11d52932196438471219af3b/package.json#L28-L30

meaning `npm install --save jquery` is required

**Comment by scottsasaki** [comment]
If you already have jQuery on the page and are using Vue Cli-3

```
  configureWebpack: {
    entry: {
      main: './src/main.js'
    },
    externals: {
      jquery: 'jQuery'
    }
```

**Comment by hmawla** [comment]
what if I'm using nuxt
