### ISSUE TITLE
@init error

### ISSUE THREAD

**Issue by ItsLhoudini** [staskjs/vue-slick#7]
Using event @init on slick like this

`<slick ref="slick" :options="slickOptions" @init="slideWidth">`

brings me this error:

`Uncaught TypeError: n.apply is not a function`

Notice: @beforeChange @afterChange .... works perfectly!

**Comment by staskjs** [comment]
I suspect that problem is not with vue-slick, because it just proxies events to original plugin. It works for me just fine.
