### ISSUE TITLE
camelCase events

### ISSUE THREAD

**Issue by MWStudio4** [staskjs/vue-slick#70]
Hello. I have trouble with camelCased events (afterChange in my case).
From console i've got this:

[Vue tip]: Event "afterchange" is emitted in component <Slick> at node_modules/vue-slick/slickCarousel.vue but the handler is registered for "afterChange". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "after-change" instead of "afterChange".

And no working event listener. I tried kebab-case and got the same error. Other 'oneword' events work fine. If i change to 'afterchange' in slick source - all is ok.

**Comment by jackleblack-kpt** [comment]
Same issue

**Comment by thanosasimo** [comment]
Same issue here using inline-template

**Comment by mrKorg** [comment]
I have the same problem. Nobody fix it?
