### ISSUE TITLE
Possibility of novigation by index 

### ISSUE THREAD

**Issue by Rim-777** [staskjs/vue-slick#75]
Hi, I'm really glad to see Slick as a Vue plugin, thx a lot.
I have a question, is there any possibility to specify the index of a slide which should be shown?
Something kind of a method like
 slideTo(index-in-array){
     }
Thanx again and looking forward to your reply.

**Comment by TitanFighter** [comment]
@Rim-777 
In the `readme` is shown the next code
data() {
    return {
        slickOptions: {
            slidesToShow: 3,
            // Any other options that can be got from plugin documentation
        },
    }

[Slick documentation](http://kenwheeler.github.io/slick/) has the next option: `slickGoTo`.
Did you try to add `slickGoTo` to `slickOptions`, something like:
```
data() {
    return {
        slickOptions: {
            slidesToShow: 3,
            slickGoTo: 5
        }
    }
},
methods: {
    slideTo(index) {
      this.slickGoTo = index
    }
}
```
?

**Comment by gfdsa** [comment]
`<Slick
      ref="some-uniq-ref"
    >`
then
`<button class="bike-image-nav" @click="slickGoTo(index)">`
and finally
`slickGoTo(index) {
      this.$refs["some-uniq-ref"].$el.slick.slickGoTo(parseInt(index));
    }
`
the above works for me.
Just setting the options.slickGoTo to an index didn't catch.
