### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [staskjs/vue-slick#8]
I have an easy example with

```
\\ a componenet .vue
...
    <slick ref="slick" :options="{slidesToShow: 3, infinite: true,  slidesToShow: 1}">
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
      </slick>
...
```

Where box is 

```
.box {
  height: 150px;
  width: 350px;
  margin-left: 5px;
  background-color: red;
}
```

With the vue chrome's extension i can see that the options are correctly passed to the slick component but this is the result:

<img width="1302" alt="screen shot 2017-02-10 at 13 33 29" src="https://cloud.githubusercontent.com/assets/15908060/22826961/89494322-ef95-11e6-91a3-5352d89a355b.png">

What is going on?

**Comment by staskjs** [comment]
This most likely has nothing to do with vue-slick, because it is just a wrapper for vue. You should better address your question to original plugin authors. But I think this is just a css problem.

**Comment by FrancescoSaverioZuppichini** [comment]
I just follow the guideline, that's it.

**Comment by mbarwick83** [comment]
I'm also getting this issue too.

**Comment by staskjs** [comment]
I would suggest adding slick css from node_modules/slick-carousel/slick/slick.css

**Comment by cviebrock** [comment]
I'm having this issue as well, but I traced it back to the fact that the HTML element that held my slick component was part of a CSS Grid element with a variable width.  i.e.:

```html
<div class="grid" style="display: grid; grid-template-columns: 200px 1fr;">
    <div class="sidebar">...</div>
    <div class="main">
        <slick ...>...</slick>
    </div>
</div>
```

I think in this case, the plugin can't determine the width of the slick-track, so everything goes a bit nuts.

**Comment by jzucadi** [comment]
So what do you do, the link doesn't have a solution that works

**Comment by cviebrock** [comment]
I needed to make sure the containing element of the `<slick>` component had a defined width. 😞

**Comment by mooc0705** [comment]
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

This is how I solved the problem. Add  'slick-carousel/slick/slick-theme.css' should fix the problem

**Comment by henridelozanne** [comment]
I had the same problem, solved it by adding

`<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>`

in my `index.html` head

**Comment by P-James** [comment]
I had this issue after running npm run prod
So I also added the cdn links to the css in my template and it works
