### ISSUE TITLE
Does not work in ie11

### ISSUE THREAD

**Issue by karamjeetiron** [staskjs/vue-slick#85]
I made three slider with vue slick. Two are working fine but there an issue in third one. It just overlapping all the content,some times images are shown ,sometimes page goes blank. I faced it only in IE11. 

`<template>
	<div class="home-banner-v2 section-gap pt-3 pb-0"> 
		<slick ref="carousel" :options="slickOptions">
			<div v-for="(sliderItem,key) in data"
				:key="key">
				<div class="banner-slide">
					<img :src="..." alt="slider-image" width="952" height="470">
					<div class="emb-banner-content">
						<h4>{{sliderItem.subHeading}}</h4>
						<h1 class='text-main'>{{sliderItem.heading}}</h1>
						<h1 class="text-bold mb-4">
							{{sliderItem.percent}}
							<sup class="bold-sup">{{sliderItem.offer}}</sup>
						</h1>
						<v-btn color="accent mt-0" to="/fashion">Shop Now</v-btn>
					</div>
				</div>
			</div>
      </slick>
	</div>
</template>
<script>
import Slick from "vue-slick";
export default {
	props: ['data'],
	components: { Slick },
	data() {
    return {
      slickOptions: {
         infinite: true,
         centerMode: true,
         centerPadding: '400px',
         slidesToShow: 1,
         slidesToScroll: 1,
         autoplay: true,
         autoplaySpeed: 2000,
         dots: false,
         arrows:false,
         rtl: this.isRTL,
         responsive: [
            {
               breakpoint: 1400,
               settings: {
                  arrows: false,
                  centerMode: true,
                  centerPadding: '300px',
                  slidesToShow: 1,
                  slidesToScroll: 1,
                  autoplay: true,
                  autoplaySpeed: 2000
               }
            },
            {
               breakpoint: 1199,
               settings: {
                  arrows: false,
                  centerMode: true,
                  centerPadding: '150px',
                  slidesToShow: 1,
                  slidesToScroll: 1,
                  autoplay: true,
                  autoplaySpeed: 2000
               }
            },
            {
               breakpoint: 899,
               settings: {
                  arrows: false,
                  centerMode: true,
                  centerPadding: '75px',
                  slidesToShow: 1,
                  slidesToScroll: 1,
                  autoplay: true,
                  autoplaySpeed: 2000
               }
            },
            {
               breakpoint: 768,
               settings: {
                  arrows: false,
                  centerMode: false,
                  centerPadding: '0',
                  slidesToShow: 1,
                  slidesToScroll: 1,
                  autoplay: true,
                  autoplaySpeed: 2000
               }
            },
            {
               breakpoint: 480,
               settings: {
                  arrows: false,
                  centerMode: false,
                  centerPadding: '0',
                  slidesToShow: 1,
                  slidesToScroll: 1,
                  autoplay: true,
                  autoplaySpeed: 2000
               }
            }
         ]
      }
    }
  }
}
</script>

`
How to fix it.

**Comment by klivak** [comment]
I had, maybe, the same error few month ago in IE11.
You may try something from this https://github.com/staskjs/vue-slick/issues/80
