### ISSUE TITLE
Some methods don't work

### ISSUE THREAD

**Issue by pieterjanmaes** [staskjs/vue-slick#86]
@afterChange="handleAfterChange"
@beforeChange="handleBeforeChange"
@setPosition="handleSetPosition"

These methods doen't work, in the vue.js.

I get the following warning:

[Vue tip]: Event "afterchange" is emitted in component <Slick> at /Users/staskjs/Projects/vue-slick/src/slickCarousel.vue but the handler is registered for "afterChange". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "after-change" instead of "afterChange".

Can someone help me out?

**Comment by enricodeleo** [comment]
I think @staskjs should take in account this https://stackoverflow.com/a/50423976/1335188

I'll do a pull request about it, if he doesn't mind

**Comment by DBZFYAM** [comment]
@enricodeleo was your pull request ever merged into the repo? As this still seems to be an issue with the latest version. Solved it woth your comment for now

**Comment by enricodeleo** [comment]
> @enricodeleo was your pull request ever merged into the repo? As this still seems to be an issue with the latest version. Solved it woth your comment for now

Actually it's still pending https://github.com/staskjs/vue-slick/pull/90 maybe not the most important merge to do, bust still it'd be useful for many

**Comment by DBZFYAM** [comment]
Cool, then I'll leave it as is for now and check back again in a while. Thanks a lot for the quickfix and the PR!
