### ISSUE TITLE
nuxt-link destroys slick instance

### ISSUE THREAD

**Issue by coreysyms** [staskjs/vue-slick#89]
After clicking on any `nuxt-link` my slick carousel is destroyed, leaving all the slides just stacked one on top the other, any ideas? Nuxt issue? vue-slick issue?

**Comment by dringala** [comment]
Hi, did you manage to find a work around for this?

**Comment by coreysyms** [comment]
honestly I dont remember, everything seems to be working ok for me. Im looking at my code and it seems I attached a "fade out" method to the button click.

`<nuxt-link :to="PATH" class="button white" @click.native="fadeoutCarousel">` which faded out the carousel after a click. Im not sure if this was a stopgap, failsafe, or visual delight.

`fadeoutCarousel () { document.getElementById('homeSlider').classList.add('loading'); }`
