### ISSUE TITLE
How to remove items in slick correctly

### ISSUE THREAD

**Issue by ignoreswing** [staskjs/vue-slick#9]
### Question description
Hi, thanks for providing this wrapper. Your code is simple and easy to understand.
Slick works fine on my vue project via vue-slick.
However, when I try to remove items in slick, I have encountered difficulties.

Remove cause the following vue's error in some case.
> Failed to execute 'insertBefore' on 'Node':The node before which the new node is to be inserted is not a child of this node. (omitted)

For example, 
1. "remove index 0 and 2 at once" => fail
2. "remove index 0 and 1 at once" => work

I provide my repo for easier debugging.

### Reproduction Link
[https://jsfiddle.net/ignoreswing/e4rz3ph7/](https://jsfiddle.net/ignoreswing/e4rz3ph7/)
Vue 2.1.10 + slick  
I use slick directly in my repo for convenience.
It would have the same problem by using vue-slick

### Steps to reproduce
1. click the second button  (remove index 0 and 2 at once)
2. console show the DOMException.
Vue get the wrong parentNode 
```
// error at
function insertBefore (parentNode, newNode, referenceNode) {
  parentNode.insertBefore(newNode, referenceNode);
}
```
### Something I have tried
- remove :key in v-for => would remove double items
- Use slickRemove without items.splice => vue status would be inconsistent
- Use items.splice without slickRemove => slick status would be inconsistent

It's the problem from mixing jQuery-plugin (i.e., slick) and vue, so I am not sure this is the right place to post this problem.
I think this is not the issue from vue-slick or vue or slick.

I would appreciate it if you could give me any hint about how to remove the items.
Thank you.

**Comment by staskjs** [comment]
Apparently vue and slick are conflicting on who should remove element from dom, but I don't understand why first button works then. My first thought was about some `rebuild` method on slick, that would look inside dom and build its inner configuration from scratch, but looks like there is no such method. Anyway it would by useful not just for vue.

**Comment by ignoreswing** [comment]
@staskjs  Thank you for your prompt reply.
I'm a newcomer to the vueJS. I have stuck this problem more than three days. 

At first, I tried to find out a method to tell vue [re-render](https://vuejs.org/v2/api/#render) or [re-compile template](https://vuejs.org/v2/api/#Vue-compile). 
The more I try the more I fail.

It's seems that dynamic DOM manipulation is not preferred for vue's style, and everything should be prepared ready before _mounted_.  (Maybe it's not true?) 

After more attempts, I found a workaround. 
What I did is as follows:
[jsfiddle](https://jsfiddle.net/ignoreswing/up86vs6r/)

Keep them separated as far as possible.
I remove vue's syntax `v-for` `<slot>` and append dom by jQuery.

I know this is not good enough. Any comments or suggestions are appreciated.

**Comment by staskjs** [comment]
Well, here is mine solution, but it is nothing better than yours.
[jsfiddle](https://jsfiddle.net/LnkoqhLh/)

Basically I tried to keep main component clean to be able to control everything from vue (without dom manipulation). I added `slick-wrap` component that keeps track of what was removed or added to items array and makes slick to all work.

P.S. not very optimized code, for the sake of example.

**Comment by ignoreswing** [comment]
I think I catch your drift.
Thank you for your hard work and help.

**Comment by staskjs** [comment]
I just made a new method called `reSlick` which basically destroys slick and reinitialises it again, redrawing what's under v-for. Try calling it when you change your data.

**Comment by ignoreswing** [comment]
I also found the similiar trick (i.e., destroy then reInitialize) at last.
However, my strategy is different.

I pass my items into vue-slick for watching the change. 
When items.length is different,  I run the reSlick.
That is to said, reSlick can be preformed automatically via vue hook.

The following is my psudo code (just partial code to show my idea)
<pre>
Vue.component('slick', {
    props: {
        items: {
            type: Array,
            default() {
                return [];
            }
        },
    },
    data: function () {
        return {
            flag: false
        };
    },
    watch: {
        items: function (nowItems, oldItems) {
            // watch item change
            if (nowItems.length !== oldItems.length) {
                this.flag = true;
            }
        }
    },
    beforeUpdate() {
        if (this.flag) {
            $(this.$el).slick('unslick');
        }
    },
    updated() {
        // try to preserve the number of slider's page instead of going to page 1.
        let page = 0, $slick = $(this.$el);
        if (this.flag) {
            page = $slick.slick('slickCurrentSlide');
            $slick
                .slick(this.options)
                .slick('slickGoTo', page, true);
            this.flag = false;
        }
    },
});
</pre>

**Comment by staskjs** [comment]
Your approach is nice too. I am happy we found a solution.
